## Imports library

In [49]:
import pandas as pd
import numpy as np

# sklearn 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler 
from sklearn.utils import resample

# Classification Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

# For Model Evaluation
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## Load Dataset

In [41]:
df=pd.read_csv("kidney_disease.csv")
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

## Data Preprocessing

In [42]:
important_columns=['age','bp','sg','al','hemo','sc','htn','dm','cad','appet','pc','classification']
df=df[important_columns]
df

,age,bp,sg,al,hemo,sc,htn,dm,cad,appet,pc,classification
0,48.0,80.0,1.020,1.0,15.4,1.2,yes,yes,no,good,normal,ckd
1,7.0,50.0,1.020,4.0,11.3,0.8,no,no,no,good,normal,ckd
2,62.0,80.0,1.010,2.0,9.6,1.8,no,yes,no,poor,normal,ckd
3,48.0,70.0,1.005,4.0,11.2,3.8,yes,no,no,poor,abnormal,ckd
4,51.0,80.0,1.010,2.0,11.6,1.4,no,no,no,good,normal,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,15.7,0.5,no,no,no,good,normal,notckd
396,42.0,70.0,1.025,0.0,16.5,1.2,no,no,no,good,normal,notckd
397,12.0,80.0,1.020,0.0,15.8,0.6,no,no,no,good,normal,notckd
398,17.0,60.0,1.025,0.0,14.2,1.0,no,no,no,good,normal,notckd
399,58.0,80.0,1.025,0.0,15.8,1.1,no,no,no,good,normal,notckd

## Short definations for the each important feature

'age': 'patient age(years)',

'bp':'Blood pressure(mm/Hg)'

'sg':Urine specific gravity

'al': Albumin in urine(0-5)

'hemo': Hemoglobin level(g/dl)

'sc': Serum creatinine(mg/dl)

'htn': Hypertension(yes/no)

'dm':'Diabetes mellitum(yes/no)

'cad':'coronary artery disease(yes/no)

'appet': 'Appetite status(good/poor)

'pc':Pus cell status (normal/abnormal)

'classification':'CKD diagnosis(ckd/notckd)

In [43]:
df.isnull().sum()

age                9
bp                12
sg                47
al                46
hemo              52
sc                17
htn                2
dm                 2
cad                2
appet              1
pc                65
classification     0
dtype: int64

## Filling Missing Values

In [44]:
df['age'].fillna((df['age']).median(),inplace=True)      #Nummerical -> median
df['bp'].fillna((df['bp']).median(),inplace=True)        #Nummerical -> median
df['sg'].fillna((df['sg']).mode()[0],inplace=True)       #categorical (discrete numeric)-> mode
df['al'].fillna((df['al']).mode()[0],inplace=True)       #Nummerical -> median
df['hemo'].fillna((df['hemo']).median(),inplace=True)    #Nummerical -> median
df['sc'].fillna((df['sc']).median(),inplace=True)        #Nummerical -> median
df['htn'].fillna((df['htn']).mode()[0],inplace=True)     #categorical (discrete numeric)-> mode
df['dm'].fillna((df['dm']).mode()[0],inplace=True)       #categorical (discrete numeric)-> mode
df['cad'].fillna((df['cad']).mode()[0],inplace=True)     #categorical (discrete numeric)-> mode
df['appet'].fillna((df['appet']).mode()[0],inplace=True) #categorical (discrete numeric)-> mode
df['pc'].fillna((df['pc']).mode()[0],inplace=True)       #categorical (discrete numeric)-> mode

df.isnull().sum()

age               0
bp                0
sg                0
al                0
hemo              0
sc                0
htn               0
dm                0
cad               0
appet             0
pc                0
classification    0
dtype: int64

In [45]:
# clean the dataset
# Strip and clean text columns
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.replace('\t', '', regex=True)

# Print value counts
print(df['cad'].value_counts())
print(df['dm'].value_counts())
print(df['classification'].value_counts())

cad
no     366
yes     34
Name: count, dtype: int64
dm
no     263
yes    137
Name: count, dtype: int64
classification
ckd       250
notckd    150
Name: count, dtype: int64

In [46]:
df

,age,bp,sg,al,hemo,sc,htn,dm,cad,appet,pc,classification
0,48.0,80.0,1.020,1.0,15.4,1.2,yes,yes,no,good,normal,ckd
1,7.0,50.0,1.020,4.0,11.3,0.8,no,no,no,good,normal,ckd
2,62.0,80.0,1.010,2.0,9.6,1.8,no,yes,no,poor,normal,ckd
3,48.0,70.0,1.005,4.0,11.2,3.8,yes,no,no,poor,abnormal,ckd
4,51.0,80.0,1.010,2.0,11.6,1.4,no,no,no,good,normal,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,15.7,0.5,no,no,no,good,normal,notckd
396,42.0,70.0,1.025,0.0,16.5,1.2,no,no,no,good,normal,notckd
397,12.0,80.0,1.020,0.0,15.8,0.6,no,no,no,good,normal,notckd
398,17.0,60.0,1.025,0.0,14.2,1.0,no,no,no,good,normal,notckd
399,58.0,80.0,1.025,0.0,15.8,1.1,no,no,no,good,normal,notckd

## Encoding

In [47]:
# Converting the dataset categorical to nummerical manually

df['htn']=df['htn'].map({'yes':1, 'no':0})
df['dm']=df['dm'].map({'yes':1, 'no':0})
df['cad']=df['cad'].map({'yes':1, 'no':0})
df['appet']=df['appet'].map({'good':1, 'poor':0})
df['pc']=df['pc'].map({'normal':1, 'abnormal':0})
df['classification']=df['classification'].map({'ckd':1, 'notckd':0})

In [48]:
df

,age,bp,sg,al,hemo,sc,htn,dm,cad,appet,pc,classification
0,48.0,80.0,1.020,1.0,15.4,1.2,1,1,0,1,1,1
1,7.0,50.0,1.020,4.0,11.3,0.8,0,0,0,1,1,1
2,62.0,80.0,1.010,2.0,9.6,1.8,0,1,0,0,1,1
3,48.0,70.0,1.005,4.0,11.2,3.8,1,0,0,0,0,1
4,51.0,80.0,1.010,2.0,11.6,1.4,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,15.7,0.5,0,0,0,1,1,0
396,42.0,70.0,1.025,0.0,16.5,1.2,0,0,0,1,1,0
397,12.0,80.0,1.020,0.0,15.8,0.6,0,0,0,1,1,0
398,17.0,60.0,1.025,0.0,14.2,1.0,0,0,0,1,1,0
399,58.0,80.0,1.025,0.0,15.8,1.1,0,0,0,1,1,0

## Scaling: Normalization

In [50]:
from sklearn.preprocessing import MinMaxScaler
# Select numerical columns to normalize
numeric_cols=['age','bp','sg','al','hemo','sc']

#Initialize scaler
scaler=MinMaxScaler()

# Fit-transorm the numerical column
df[numeric_cols]=scaler.fit_transform(df[numeric_cols])

df.head()

,age,bp,sg,al,hemo,sc,htn,dm,cad,appet,pc,classification
0,0.522727,0.230769,0.75,0.2,0.836735,0.010582,1,1,0,1,1,1
1,0.056818,0.000000,0.75,0.8,0.557823,0.005291,0,0,0,1,1,1
2,0.681818,0.230769,0.25,0.4,0.442177,0.018519,0,1,0,0,1,1
3,0.522727,0.153846,0.00,0.8,0.551020,0.044974,1,0,0,0,0,1
4,0.556818,0.230769,0.25,0.4,0.578231,0.013228,0,0,0,1,1,1

## Data Balancing

In [51]:
df['classification'].value_counts()

classification
1    250
0    150
Name: count, dtype: int64

In [55]:
#!pip install imbalanced-learn

In [56]:
from imblearn.over_sampling import SMOTE, RandomOverSampler  # To handle data imbalance

# Separate features and target
x = df.drop('classification', axis=1)
y = df['classification']

# Apply SMOTE
smote = SMOTE(random_state=42)
x_balanced, y_balanced = smote.fit_resample(x, y)

In [57]:
y_balanced.value_counts()

classification
1    250
0    250
Name: count, dtype: int64

## Train Test Split

In [59]:
# Split into train and test sets(80% train, 20% test)
X_train,X_test, y_train, y_test=train_test_split(x_balanced,y_balanced, test_size=0.2, random_state=42)

# check the shape
print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

Train shape: (400, 11)
Test shape: (100, 11)

## Trainig, Testing Multiple Classifiers

In [63]:
# Define the models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Support Vector Classifier": SVC(probability=True, random_state=42),
    "Random Forest Classifier": RandomForestClassifier(random_state=42),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(random_state=42),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(random_state=42),
    "Gradient Boosting Classifier": GradientBoostingClassifier(random_state=42),
}

In [66]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"{name} Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print("-" * 60)

Logistic Regression Accuracy: 0.9600
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        54
           1       1.00      0.91      0.95        46

    accuracy                           0.96       100
   macro avg       0.97      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100

[[54  0]
 [ 4 42]]
------------------------------------------------------------
Support Vector Classifier Accuracy: 0.9700
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        54
           1       1.00      0.93      0.97        46

    accuracy                           0.97       100
   macro avg       0.97      0.97      0.97       100
weighted avg       0.97      0.97      0.97       100

[[54  0]
 [ 3 43]]
------------------------------------------------------------
Random Forest Classifier Accuracy: 1.0000
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00        46

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

[[54  0]
 [ 0 46]]
------------------------------------------------------------
K Nearest Neighbors Accuracy: 0.9700
              precision    recall  f1-score   support

           0       0.95      1.00      0.97        54
           1       1.00      0.93      0.97        46

    accuracy                           0.97       100
   macro avg       0.97      0.97      0.97       100
weighted avg       0.97      0.97      0.97       100

[[54  0]
 [ 3 43]]
------------------------------------------------------------
Decision Tree Classifier Accuracy: 0.9900
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       1.00      0.98      0.99        46

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

[[54  0]
 [ 1 45]]
------------------------------------------------------------
Gaussian Naive Bayes Accuracy: 0.9600
              precision    recall  f1-score   support

           0       0.93      1.00      0.96        54
           1       1.00      0.91      0.95        46

    accuracy                           0.96       100
   macro avg       0.97      0.96      0.96       100
weighted avg       0.96      0.96      0.96       100

[[54  0]
 [ 4 42]]
------------------------------------------------------------
AdaBoost Classifier Accuracy: 1.0000
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        54
           1       1.00      1.00      1.00        46

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

[[54  0]
 [ 0 46]]
------------------------------------------------------------
Gradient Boosting Classifier Accuracy: 0.9900
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       1.00      0.98      0.99        46

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

[[54  0]
 [ 1 45]]
------------------------------------------------------------

## Selecting the Best Model

In [72]:
model_gbc=GradientBoostingClassifier()
model_gbc.fit(X_train,y_train)
y_pred=model_gbc.predict(X_test)

print("confusion matrix \n:", confusion_matrix(y_test,y_pred))
print("classification report\n:", classification_report(y_test,y_pred))

confusion matrix
: [[54  0]
 [ 1 45]]
classification report
:               precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       1.00      0.98      0.99        46

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

## Saving Model, Encoder, Scaler for production

In [74]:
import os
import pickle

# Create directory if it doesn't exist
os.makedirs("models", exist_ok=True)

# Save scaler and model
pickle.dump(scaler, open("models/scaler.pkl", 'wb'))
pickle.dump(model_gbc, open("models/model_gbc.pkl", 'wb'))

## Inference (Prediction on new data)

In [78]:
# Load the encoder, scaler, and trained model from saved file
scaler=pickle.load(open("models/scaler.pkl",'rb')) # Load the scaler
model_gbc=pickle.load(open("models/model_gbc.pkl",'rb')) # Load the trained model

In [89]:
def predict_chronic_disease(age, bp, sg, al, hemo, sc, htn, dm, cad, appet, pc):
    df_dict = {
        'age': [age],
        'bp': [bp],
        'sg': [sg],
        'al': [al],
        'hemo': [hemo],
        'sc': [sc],         
        'htn': [htn],
        'dm': [dm],
        'cad': [cad],
        'appet': [appet],
        'pc': [pc]
    }
    df = pd.DataFrame(df_dict)

    # Encode categorical
    df['htn'] = df['htn'].map({'yes': 1, 'no': 0})
    df['dm'] = df['dm'].map({'yes': 1, 'no': 0})
    df['cad'] = df['cad'].map({'yes': 1, 'no': 0})
    df['appet'] = df['appet'].map({'good': 1, 'poor': 0})
    df['pc'] = df['pc'].map({'normal': 1, 'abnormal': 0})

    numeric_cols = ['age', 'bp', 'sg', 'al', 'hemo', 'sc']
    df[numeric_cols] = scaler.transform(df[numeric_cols])

    prediction = model_gbc.predict(df)

    return prediction[0]

In [90]:
result = predict_chronic_disease(
    age=65,
    bp=100,
    sg=1.030,
    al=3.0,
    hemo=9.0,
    sc=1.020, 
    htn="yes",
    dm="yes",
    cad="yes",
    appet="poor",
    pc="abnormal"
)
print("Prediction:", "Chronic Disease Detected" if result == 1 else "No Chronic Disease")

Prediction: Chronic Disease Detected

In [91]:
import sklearn

print(sklearn.__version__)

1.3.2